server:
  port: 9092

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://192.168.1.25:5432/wanim_DB
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: update
  cloud:
    compatibility-verifier:
      enabled: false